Repository levxyca/pandadomalbot, pull requests merged in 2022-02, with the labels that each got.

#211 Movendo configuração do eslint/prettier para os arquivos específicos
  .eslintrc.js
  .prettierrc.js
  .vscode/extensions.json
  .vscode/settings.json
  package.json
Labels: enhancement

#212 Atualizando dependências
  package-lock.json
  package.json
  src/queues/people.js
Labels: enhancement

#214 Adicionando funcionalidade de resposta automática
  src/autoreply/ola.js
  src/commands/comandos.js
  src/events/chat.js
  src/utilities/bot-fs.js
Labels: enhancement, refactoring

#207 Migrando comando `!lev` e adicionando `!apostaLev`
  .env.example
  src/commands/fun/_constants.js
  src/commands/fun/aposta-lev.js
  src/commands/fun/lev.js
Labels: enhancement, refactoring

#220 Permitindo indentação nos arquivos arquivos JSON do diretório '/data'
  .env.example
  src/utilities/data-file.js
Labels: enhancement

#219 Classe para agrupar todos os atributos dos usuários
  .eslintrc.js
  .vscode/settings.json
  src/commands/fun/aposta-lev.js
  src/models/person.js
  src/queues/people.js
Labels: refactoring

#223 Adicionando docs sobre como contribuir com o projeto
  .github/docs/como-contribuir.md
  .github/docs/como-executar.md
Labels: documentation

#222 Migrando o comando `!pontos`
  src/commands/pontos.js
Labels: refactoring

#228 Incluindo recurso para obter os usuários online no chat
  package-lock.json
  package.json
  src/utilities/twitch.js
Labels: enhancement, refactoring

#229 Adicionando recurso para criação de rotinas de repetição
  .github/docs/como-contribuir.md
  .github/docs/criando-comandos-de-resposta-automatica.md
  .github/docs/criando-novos-comandos.md
  .github/docs/criando-rotinas-de-repeticao.md
  src/events/connected.js
  src/events/index.js
  src/index.js
  src/loops/commands.js
Labels: refactoring

#231 Migrando lembrete de retweet
  src/loops/retweet.js
Labels: refactoring

#227 Refatorando os comandos da prisão
  .env.example
  .eslintrc.js
  src/commands/jail/escapar.js
  src/commands/jail/presos.js
  src/commands/jail/proteger.js
  src/commands/jail/protegido.js
  src/commands/jail/salvar.js
  src/loops/prender-viewers.js
  src/models/jail.js
  src/queues/jail.js
  src/utilities/twitch.js
Labels: refactoring

#241 feat: Create autoreply to 'eita'
  .gitignore
  src/autoreply/eita.js
Labels: refactoring

#243 feat: Create autoreply to 'Kappa'
  src/autoreply/kappa.js
Labels: refactoring

#242 feat: Create piada command
  src/commands/fun/piada.js
  src/utilities/collections.js
Labels: refactoring

#245 Refatorando o uso da função `sample`
  src/commands/fun/aposta-lev.js
  src/commands/fun/lev.js
  src/commands/jail/escapar.js
  src/models/jail.js
  src/utilities/collections.js
Labels: 🏗 refactoring

#246 Adicionando o comando `!rank`
  src/commands/rank.js
  src/queues/people.js
Labels: 🏗 refactoring

#240 Dando pontos ao usuário que der subgift
  .env.example
  src/events/index.js
  src/events/subgift.js
  src/index.js
Labels: 💡 enhancement

#248 feat: create pergunta command
  src/commands/fun/pergunta.js
Labels: 🏗 refactoring

#251 Skippando consulta de tweet se variáveis não estiverem definidas
  src/commands/rt.js
  src/core/twitter_client.js
  src/loops/retweet.js
Labels: 💡 enhancement

#247 Exportando comandos do bot
  .github/docs/criando-novos-comandos.md
  .gitignore
  package.json
  src/export.js
Labels: 💡 enhancement

#256 Adicionando comandos de divulgação
  src/commands/publicize/capturar.js
  src/commands/publicize/caraio.js
  src/commands/publicize/selva.js
  src/commands/publicize/spin.js
Labels: 🏗 refactoring

#260 Adicionando o comando `!ensinamento`
  src/commands/fun/ensinamento.js
Labels: 🏗 refactoring

#261 Migrando "padrão"
  src/autoreply/padrao.js
  src/events/chat.js
Labels: 🏗 refactoring

#262 Corrigindo padrão
  src/autoreply/padrao.js
Labels: 🐛 bug
